### ISSUE TITLE
[PE-D] (Quiz commands) Prev/next incorrect message shown

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-1/tp#159]
![Screenshot 2021-10-29 at 4.47.01 PM.png](https://raw.githubusercontent.com/chongjunwei/ped/main/files/193b23db-53ee-4aa1-9bbc-601ea0cc94ac.png)

Should be "Go to" instead of "Got", same error for the next command

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: chongjunwei/ped#11

**Comment by ryanpeh** [comment]
This is intended.
However, we'll add it into the user guide such that it is clear that this is intentional.
