### ISSUE TITLE
[PE-D] Missing command in User guide Command Summary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-1/tp#166]
![Screenshot 2021-10-29 at 4.52.54 PM.png](https://raw.githubusercontent.com/SHEZADHASSAN22/ped/main/files/3bc58b54-8435-4fb0-a899-b51154d234db.png)

The saq and tf instructions are not included where I think they should be.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: SHEZADHASSAN22/ped#6

**Comment by neojxuan** [comment]
Duplicate of #167
