### ISSUE TITLE
[PE-D] Insufficient visuals for UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-1/tp#181]
The user guide has insufficient visuals. It was mostly textual and heavy on reading. Perhaps more screenshots or diagrams could enhance the readability and digestibility of certain commands, especially the adding of question types commands. Also, could use screenshots to show the difference between the quiz and the normal window, which serves as a good text buffer to reduce chunky text portions.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: yeo-yiheng/ped#11

**Comment by Agentum07** [comment]
Fixed in recent documentation spree.
