### ISSUE TITLE
[PE-D] User guide lacks visuals 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-1/tp#182]
I think it would be good to include more screenshots and diagrams to show users how the app is suppose to work. It would help the users to visualize and understand certain features such as stats or notes. 

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: greyguy21/ped#11

**Comment by ryanpeh** [comment]
Duplicate of https://github.com/AY2122S1-CS2103T-F12-1/tp/issues/182, closing.
