### ISSUE TITLE
Tag names should be alphanumeric not documented

### ISSUE THREAD

**Issue by ryanpeh** [AY2122S1-CS2103T-F12-1/tp#217]
Tag names should be alphanumeric is not specified in user guide.

![image](https://user-images.githubusercontent.com/8349091/140354700-1da043d9-9270-4cad-a3b0-006396cff215.png)

**Comment by Agentum07** [comment]
Done [here](https://github.com/AY2122S1-CS2103T-F12-1/tp/pull/242)
