### ISSUE TITLE
Feat: Start a quiz 

### ISSUE THREAD

**Issue by aryagiat** [AY2122S1-CS2103T-F12-1/tp#5]
## Issue Type
Feature

## Current Status
Users can add questions and answers but cannot test themselves.

## Desired Status
Allow users to quiz themselves.

## Technical Implementation
- Create a `Quiz` class
- Store a list of `Questions` inside the class
![image](https://user-images.githubusercontent.com/55704015/134464764-5e0c60f1-deac-4c83-ac9a-f634e7f12bfd.png)

**Comment by ryanpeh** [comment]
Addressed in https://github.com/AY2122S1-CS2103T-F12-1/tp/pull/33
